### ISSUE TITLE
COC DB ERROR Error: no adapter for postgres

### ISSUE THREAD

**Issue by oblitum** [kristijanhusak/coc-db#1]
I get

```
DEBUG (pid:75108) [extension-coc-db] - COC DB ERROR Error: request error nvim_call_function - DB: no adapter for postgres
```

when trying out the extension. I'm using `vim-dadbod-ui` and have `$DBUI_URL` correctly set, dadbod-ui works and I can browse db and make queries, just `coc-db` completion isn't working for some reason.

**Comment by kristijanhusak** [comment]
Yeah this is something that i have issue with also, wasn't able to figure it out.
Workaround is to use `postgresql` instead of `postgres` in your db url.

**Comment by kristijanhusak** [comment]
I fixed it, give it a test.

**Comment by oblitum** [comment]
Working great now, thanks, awesome extension!
